name: Continuous Integration
 
on: 
  pull_request:
    branches:
      - submission-2-ci
      - master
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install migrate and test
      run: |
        npm install
        npm run migrate up
        npm run test
      env:
        CI: true
        PGHOST_TEST: ${{ secrets.PGHOST_TEST }}
        PGUSER_TEST: ${{ secrets.PGUSER_TEST }}
        PGDATABASE_TEST: ${{ secrets.PGDATABASE_TEST }}
        PGPASSWORD_TEST: ${{ secrets.PGPASSWORD_TEST }}
        PGPORT_TEST: ${{ secrets.PGPORT_TEST }}
        PGHOST: ${{ secrets.PGHOST_TEST }}
        PGUSER: ${{ secrets.PGUSER_TEST }}
        PGDATABASE: ${{ secrets.PGDATABASE_TEST }}
        PGPASSWORD: ${{ secrets.PGPASSWORD_TEST }}
        PGPORT: ${{ secrets.PGPORT_TEST }}
        ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
        REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}